### ISSUE TITLE
Suggestion for debugging statements

### ISSUE THREAD

**Issue by shakram02** [yomnabarakate21/Registeration-website#2]
the `echo` function prints to the HTML, which might not be the best solution for all cases, you might want to consider printing the debug messages using something else.

Using a [log file](https://stackoverflow.com/questions/6079492/how-to-print-a-debug-log)
Using the [browser console](https://paulund.co.uk/output-php-data-in-browser-console)

**Comment by yomnabarakate21** [comment]
This was just for a trial.
It will be changed though.

**Comment by shakram02** [comment]
Best of luck :four_leaf_clover:
